name: hotjar
description: Javascript interop for Hotjar
version: 0.1.0
homepage: https://github.com/leftyio/hotjar

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.3
  dart_browser_loader: ^0.1.0

dev_dependencies:
  test: ^1.16.0
  pedantic: ^1.10.0
  build_runner: ^1.10.0
  build_web_compilers: ^2.15.0
