name: hotjar
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://lefty.io
author: Lejard Hadrien <hadrien.lejard@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  js: ^0.6.1
  dart_browser_loader: ^0.0.4

dev_dependencies:
  test: ^0.12.0
