name: hotjar
description: Javascript interop for Hotjar
version: 0.0.4-nullsafety.0
homepage: https://github.com/leftyio/hotjar

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  js: ^0.6.3-nullsafety.3
  dart_browser_loader: ^0.0.7-nullsafety.0

dev_dependencies:
  test: ^1.16.0-nullsafety.0
  pedantic: ^1.10.0-nullsafety
  build_runner: ^1.10.0
  build_web_compilers: ^2.15.0
